# KRaft controller (Hiljaisuus)
# Hex: (0,0,0)

process.roles=controller
node.id=0
controller.quorum.voters=0@kuule-hex-0-0-0:9093

# Network
listeners=CONTROLLER://:9093
listener.security.protocol.map=CONTROLLER:PLAINTEXT
controller.listener.names=CONTROLLER

# Storage (metadata only)
log.dirs=/var/lib/kafka/data

# Minimal threads
num.network.threads=1
num.io.threads=1
